### ISSUE TITLE
Update href in code snippet to be SE-friendly

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/react-accordion-html-generator#15]
The [Accrdionater](https://www.bcpl.info/_tools/accordionater.html) currently generates heading anchors in a format that SE doesn't like. We need a slightly different format in order for accordions to display correctly.

When code is output, each panel's anchors are created in the format `href="#panel-1"`. We need to to be formatted as `href="https://#panel-1"`.

Please check in with me if a more detailed descritpion is needed.

**Comment by danfox01** [comment]
@sgrg1 I think you said this one just needs to be moved to dev, right? I believe the dev refresh is happening this morning. Once it's done, can we get this in place for testing?

**Comment by tmccoy529** [comment]
@danfox01 @sgrg1 same issue here with the pinning. Trying to get Sanajay's code compiled so it can be moved to SE for testing. Looking at lunch time today. (Yarn is what we are using instead of gulp for these react projects and he has to get Yarn working).

**Comment by tmccoy529** [comment]
@danfox01 this is ready for testing

**Comment by danfox01** [comment]
This looks good to me. @jdomasky can you test this as well? I can fill you in on a test case.

**Comment by jdomasky** [comment]
@danfox01 No problem--I can test today around mid-afternoon. I'll check in with you via Hangouts for the test case.

**Comment by jdomasky** [comment]
@tmccoy529 @sgrg1 @danfox01 The Accordionater in dev tested perfectly for this issue. Thumbs up!

**Comment by danfox01** [comment]
Thanks! @martypowell can confirm, but since this is just an internal tool and separate code, I think we can push it to production whenever. I don't see any risk.

**Comment by martypowell** [comment]
@tmccoy529 @sgrg1 I haven't seen any pull requests for this. That would be the next step.

**Comment by sdurphy** [comment]
The accordionater is working in prod. Confirmed with test page here: https://www.bcpl.info/_test/accordion-test.html. Thanks everyone.
